import "@/globals.css";
import NextAuthSessionProvider from "@/providers/SessionProvider";
import { getServerSession } from "next-auth/next";
import type { Metadata } from "next";
import { nextAuthOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function PrivateLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Antes de renderizar páginas nesse grupo de rotas, irei verificar
  // se o usuário está logado. Se não estiver, irei redirecionar para a
  // a página de login
  const session = await getServerSession(nextAuthOptions)

  if (!session) {
    redirect("/auth/login");
  }

  return (
    <html lang="en">
      <body >
        <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
      </body>
    </html>
  );
}
